data:
  type: nlpcc
  base_path: 'data/'
  line_fname: 'train.txt'
  processed_path: 'processed_nlpcc_data_formal'

  word_threshold: 2
  max_seq_length: 100
  sentence_diff: 0.33
  testset_size: 25000

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 12
  num_layers: 3
  num_units: 256
  embed_dim: 512
  embed_share: true
  cell_type: gru
  dropout: 0.2
  encoder_type: bi
  attention_mechanism: normed_bahdanau

train:
  learning_rate: 0.001
  sampling_probability: 0.4

  train_steps: 1000
  model_dir: 'logs/nlpcc'

  save_checkpoints_steps: 1000
  loss_hook_n_iter: 1000
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

  print_verbose: True
  debug: False

predict:
  beam_width: 0
  length_penalty_weight: 1.0

slack:
  webhook_url: ""
